### ISSUE TITLE
EEGLab EDF+ events misplaced and wrongly named

### ISSUE THREAD

**Issue by faimai00** [eeglabdevelopers/eeglab#267]
### Description

I am loading EEG files in EDF+ format using the EEG = pop_biosig function (MATLAB_R2020b). 
When I plot them (pop_eegplot(EEG)) the events appear all grouped at the beginning of the recording, and all have the same name. This should not be the case, as the events should be marking specific events across the file, and should also not all be named the same way. 
The information contained in the EEG.event matrix reflect this (see screenshot). 

Please would you be able to help? How can I import these so the events fall on the correct locations and have correct naming?
Many thanks in advance - any advice would be greatly appreciated. 

Irene 
<img width="1204" alt="Screenshot 2021-03-10 at 15 01 58" src="https://user-images.githubusercontent.com/63585229/110650238-47945f80-81b2-11eb-9530-f12a9218645b.png">
<img width="508" alt="Screenshot 2021-03-10 at 15 02 49" src="https://user-images.githubusercontent.com/63585229/110650264-4c591380-81b2-11eb-9685-55c30bc456ae.png">

<br>
#### Steps to Reproduce
EEG = pop_biosig('/Volumes/Ashur DT2/EEG/RKS10/RawData.EDF')
pop_eegplot(EEG)

<br>
#### Expected behavior: events are loaded with correct names throughout the file

<br>
#### Actual behavior: events all have the same name, and they are all grouped in the beginning of the recording.

<br>
#### Versions
| OS version     | 10.15.7 (Catalina) |
| Matlab version | R2020b |
| EEGLAB version | eeglab2021.0 |

**Comment by arnodelorme** [comment]
Would you mind to share the EDF file. Cedric @amisepa  is our EDF expert :-). Cedric would you mind having a look?

**Comment by faimai00** [comment]
Of course - thank you so much @arnodelorme and @amisepa. Please find the EDF+ file here: https://drive.google.com/drive/folders/1SYpc6UMnbe-ip4lRB_cD_Eq1HCRP9e9I?usp=sharing

This is just one file, but I am having the same problem with all of the recordings I have. 

Many thanks.
Irene

**Comment by amisepa** [comment]
Hi,

During import, have you tried using the checkbox entitled "Import using alternative BIOSIG method (mexSLOAD)"?

Cedric

**Comment by faimai00** [comment]
Dear Cedric,

thank you for your email.
Sorry - I am not sure where I can find the checkbox. Could you please specify further?

Many thanks.
Irene
________________________________

**Comment by amisepa** [comment]
It's in the pop-up window during importation:
![image](https://user-images.githubusercontent.com/58382227/110835142-449d7b80-8253-11eb-8164-047ecfe52f0a.png)

It's not working though I just tried with your file. You seem to have custom event names that contain spaces and are too long.  I'll work on an alternative solution asap.

Cedric

**Comment by faimai00** [comment]
Thank you so much - I really appreciate it.
Irene
________________________________

**Comment by amisepa** [comment]
Hi,

It should work now if you pull eeglab,

Let me know!

**Comment by arnodelorme** [comment]
Cedric, I was looking at the 'makeur' command you mention erase the event structure. Would you mind to find an example. This command should not affect at all the event structure except for adding a "urevent" field.

**Comment by faimai00** [comment]
Hi @amisepa, thank you for that. However after updating EEGLab I still cannot read the file properly. Nothing has changed. Did it work for you? 

I am not sure if it is relevant but I don't have the option of importing using alternative BIOSIG method (mexSLOAD). I am using EEGLab 2021.0: 
<img width="716" alt="Screenshot 2021-03-17 at 09 50 44" src="https://user-images.githubusercontent.com/63585229/111448373-40b3a280-8706-11eb-831d-b1781bf60b42.png">

**Comment by faimai00** [comment]
@amisepa may I please also ask if there is anything I can do differently in how I annotate and export the EDF+ files, or whether the problem is purely on the MatLab import end? Many thanks!
Irene

**Comment by amisepa** [comment]
Do you use git?
You probably need to install eeglab with this command: git --recurse-submodules https://github.com/sccn/eeglab.git @arnodelorme is that why she doesn't have the new window?

Sorry I forgot to add to my message this piece of information:

Your data is EDF+D (discontinuous) so you need to convert it to EDF+C with EDFBrowser for example. Sorry, I don't have a better option for now so you'll have to do that for each file manually, but at least it works.
1) download EDFBrowser here: https://www.teuniz.net/edfbrowser/
2) Tools > convert to EDC+C
This will create several small files (because your data is discontinuous)
![image](https://user-images.githubusercontent.com/58382227/111494359-9f275380-86fb-11eb-8e04-b72746b382f5.png)

3) in eeglab > Import > eglab functions > from EDF/EDF+ (biosig toolbox)
Untick import EDF+ annotations and tick 'Import using alternative method'

4) Then you'll need to do this for each sub-file and merge them (https://sccn.ucsd.edu/wiki/Set_merge)
You do for example:
`EEG1= EEG;`
import next file
`EEG2= EEG;`
import next file
`EEG3 = EEG;`
... etc

`EEG = set_merge(EEG1,EEG2,EEG3)`

To save time, you can import each dataset with the command line:
```
EEG1 = pop_biosig('file_path\RawData_0001.edf', 'importannot','off','importmex','on');
EEG2 = pop_biosig('file_path\RawData_0002.edf', 'importannot','off','importmex','on');
EEG3 = pop_biosig('file_path\RawData_0003.edf', 'importannot','off','importmex','on');
EEG = set_merge(EEG1,EEG2,EEG3)
```

Let me know if this works for you.

As for your second question, I have never recorded EDF data so I cannot advise on that sorry. You might look if you can change settings in your recording software to record the data as EDF or EDF+C directly to avoid the conversion. 
And making the annotations simple numbers or codes (e.g T1, T2, etc.) is generally better than characters. 

Cedric

**Comment by faimai00** [comment]
Dear Cedric, 
Thank you very much for your help and detailed instructions. I have converted to EDF+C and the events are now positioned in the right place, however they still have all the same name. 
I have cloned the repository, but I still can't see the new window for some reason so I cannot import using alternative BIOSIG method. Is that probably why the event names keep being incorrect? 
Would you please have any advice for how to update to the new window? I have re-downloaded the last version of EEGLab + went through git cloning, but I still get the same window as the one in the screenshot I posted above. 
Many thanks again for your precious help! 
Irene

**Comment by amisepa** [comment]
Yes you need the new window to have the fixed annotations.

Did you use this line in your terminal to install eeglab?
`git clone --recurse-submodules https://github.com/sccn/eeglab.git`

I would delete the old eeglab folder, re-install using the line above, and make sure the Matlab path is updated to the new eeglab folder.

I think that is what you need to get the new changes.

**Comment by faimai00** [comment]
Dear Cedric,

thank you very much for this. I have done what you said and I am able to see the new changes now. 
I am so sorry to bother with this, but I am experiencing more problems and I still cannot get to open the files correctly. 

Initially I could not tick the box "Import using alternative method" because of an error message saying that mexSLOAD was not installed. I have then downloaded mexSLOAD from https://pub.ist.ac.at/~schloegl/src/mexbiosig/ and pasted it into my eeglab folder. I am now able to tick the box "import using alternative method", but as soon as I press OK this error comes out (see screenshot). I can see that line 238 of pop_biosig() is the following:    
237       if strcmpi(g.importmex, 'on')
238        [s,HDR] = mexSLOAD(filename); 

I have tried downloading multiple mexSLOAD files from pub.ist.ac.at but no-one seems to work. Does any solution to this come to your mind?
Thank you so much again and sorry about this. I spent several hours on it but I could not solve the problem. 

<img width="1148" alt="Screenshot 2021-03-18 at 15 05 10" src="https://user-images.githubusercontent.com/63585229/111649283-222fd300-87fc-11eb-9e3a-e7254aa67d50.png">

**Comment by amisepa** [comment]
Hi,

You don't need to download the mex files, they are already in the Biosig plugin in eeglab when you install it. 
It might be due to an update we did yesterday to improve this function. 

Are you on Mac or Windows? Did you install the bisoig toolbox via eeglab GUI first?

It is working on my side now, I followed these steps:

1) Convert EDF files to EDF+C. This should give you 5 files right? 
![image](https://user-images.githubusercontent.com/58382227/111679982-f6eabb00-87de-11eb-99f1-f8d1a5a826ed.png)
2) clone eeglab with git clone --recurse-submodules link
3) add path to eeglab folder in matlab
4) File > import EDF data with eeglab > pop-up window "do you want to install Biosig toolbox?" > Yes
5) select one of the files created by EDFBrowser
6) UNCHECK the "Import EDF+ annotations" box and CHECK the "Import using alternative Biosig method (mexsload)" box
7) Plot channel data (scroll)

**Comment by faimai00** [comment]
Hi. I am using mac (OS version | 10.15.7 (Catalina)). I did install biosig via the eeglab GUI. It shown within matlab plugins as Biosig3.7.5. 
However no luck unfortunately.... It looks like the mexSLOAD file is not there (see screenshot). Can it be a problem with the files I get from the EDF converter? I get those 5 files with exactly the same naming you have, but EDFBrowser cannot read them (see screenshot). 
Thanks!
 
<img width="417" alt="Screenshot 2021-03-19 at 12 51 57" src="https://user-images.githubusercontent.com/63585229/111783217-e5beae80-88b1-11eb-9c49-9d3a1cf3b351.png">

<img width="528" alt="Screenshot 2021-03-19 at 12 47 58" src="https://user-images.githubusercontent.com/63585229/111782885-78ab1900-88b1-11eb-9775-2f57ab7fd952.png">

**Comment by Teuniz** [comment]
> I get those 5 files with exactly the same naming you have, but **EDFBrowser cannot read them**

Sorry for barging in like this.
You are probably using an older version of EDFbrowser.
Please make sure you are using the latest version of EDFbrowser and convert the files again.
At this moment, the latest version is 1.82.
Older versions can create invalid EDF+ files when using the EDF+D to EDF+C converter, depending on the content of the recording field.
From here it seems you are probably using version 1.77 for Mac which is affected by this bug.
Regards,
Teunis

**Comment by faimai00** [comment]
Dear Teunis, 
thank you for that. Unfortunately the last version available that I can see for mac is v1.77. I will see if I can find a way around this somehow. 
So do you think that the problem is actually the way the EDFs are created, rather than anything on eeglab then? 
Many thanks for your great help @amisepa and @Teuniz, I really appreciate it!

**Comment by Teuniz** [comment]
> So do you think that the problem is actually the way the EDFs are created, rather than anything on eeglab then?

I don't know but it's likely.
You can compile EDFbrowser from source, there's a howto at the end of the README file that comes with the sourcecode that describes how to compile on the Mac.
Otherwise, run the Linux- or windows version in a virtual machine.

**Comment by amisepa** [comment]
Hi,

Thanks @Teuniz for helping on this, I don't know the details about EDFBrowser.

1) step 1: @faimai00 I can read them successfully in Windows version 1.82. Can you compile it from source as Teuniz suggested?

2) step 2: @arnodelorme I think you added recently the correct mexSLOAD for Mac. Faimaz gets an error saying it is not installed in her Biosig toolbox (see above), could you please check why or send her the appropriate file for Mac?
It should be located with the other ones in ...\plugins\Biosig3.7.5\biosig\t200_FileAccess

3) @faimai00 Do you have the Signal processing toolbox installed on your Matlab 2020b? if so, we can try another approach in the meantime. 

Cedric

**Comment by faimai00** [comment]
Hi Cedric, 
many thanks. I have just downloaded the signal processing toolbox so very happy to try any alternative method in the meantime @amisepa . 
I will try to compile EDF browser from source tomorrow anyways and see what happens. 
The directory you kindly gave in point 2 does not actually include a file for mac in my folder so if you could point me to the right file @arnodelorme I would be really grateful as I have tried a few but could not get them to work. Thank you so much all for your support!

**Comment by faimai00** [comment]
Dear @amisepa and @arnodelorme, just checking if there has been any progress with this? Thank you!

**Comment by faimai00** [comment]
I have now converted the files to EDF+C with the latest version of EDFbrowser for Windows. That appears not to be the problem as I get the same error messages regarding mexSLOAD not being installed. If I install the mexSLOAD Mac file myself from https://pub.ist.ac.at/~schloegl/src/mexbiosig/, the error message I get regards the mex file being invalid.  
Thank you.

**Comment by amisepa** [comment]
Hi @faimai00,

Sorry, been very busy!

I have worked on the alternative method when I could, but it was harder than I thought because of the discontinuous nature of your data (mainly with the event latencies). Just curious, what system is this?

I've come up with this script attached that works only with the **Signal Processing Toolbox on Matlab 2020b** or later. You don't need to convert to EDF+C with this one. 

Just add path to this script, and import your file directly with:
```
eeglab
EEG = import_EDFplusD();   %pop-up 
% EEG = import_EDFplusD(filePath)
pop_eegplot(EEG, 1, 0, 1);
figure; pop_spectopo(EEG, 1, [], 'EEG' , 'freq', [6 10 22], 'freqrange',[1 80],'electrodes','off');

```

I've just compared the result briefly with what is displayed in EDFBrowser. It looks ok so far, **but please run more tests to make sure everything is correct! Especially the markers!** 

Let me know how it goes.

Cedric

[import_EDFplusD.zip](https://github.com/sccn/eeglab/files/6240422/import_EDFplusD.zip)

**Comment by faimai00** [comment]
Dear Cedric,
thank you very much for all your work and for coming up with this! 
I have tried it. The order of the labels across the recording seem fine, however I think that the events are still getting misplaced. In the past week I have tried an edf import function that a colleague of mine has written, and there is discrepancy between where the events get positioned (see screenshots). 

Based on observation of the recordings and where the events fall, I think that the latencies obtained with import_EDFplusD are inaccurate. Also, these differ from the ones obtained by pop_biosig when "import EDF+ annotations" is checked. 

My plan I think will be to still use the pop_biosig function (with import EDF+ annotations checked, as I cannot check the alternative method mexSLOAD box). With this, I get the events positioned correctly but with the wrong name. I will then rename them based on the events order that I get with either import_EDFplusD or the experimental edf import function. It is a bit tedious but I think it can work. What do you think?
Many thanks again! 
Irene 

PS The system where I am exporting data from is the Natus EEG software

<img width="790" alt="Screenshot 2021-04-01 at 15 13 02" src="https://user-images.githubusercontent.com/63585229/113307464-0e589680-92fd-11eb-8830-7bd98ae4c70e.png">
<img width="647" alt="Screenshot 2021-04-01 at 15 14 28" src="https://user-images.githubusercontent.com/63585229/113307480-1284b400-92fd-11eb-8266-cb29941dc1eb.png">

**Comment by amisepa** [comment]
Hi,

Sorry I got the sampling rate wrong. The latencies are in ms, so you would have the following latencies in seconds with the correct sample rate: 1.998; 2.808; 2.92; etc.
Here is it is fixed. 
[import_EDFplusD.zip](https://github.com/sccn/eeglab/files/6246829/import_EDFplusD.zip)

Maybe I missed something, but I believe your latencies are incorrect. The durations between events seem to correspond, but I think the start time is wrong in either your method or mine. I adjusted the start time based on the actual time stamps of the EEG data. I see the same ones as yours in info.Annotations. Not sure why they are different. And I corrected latencies for gaps between segments, whereas in your screenshot you still have the gaps (with no EEG data) included that need adjustment. 


Comparing my latencies from segment 1 to the ones from EDFBrowser(1st segment converted to C+ with EDFBrowser), which are likely the correct ones:
![image](https://user-images.githubusercontent.com/58382227/113359685-229c9380-92fd-11eb-8812-227b5f501662.png)

If you set a breakpoint line 120 of my function and launch it, you can look at the ev structure containing, event type, correct latency, data segment it belongs to, and corresponding gaps removed. You can then compare the correct latencies with EDFBrowser (after they are converted in each segment of EDF+C). 
I've looked briefly at a few events and their differences in duration in segments 1 and 2 and they seem to match. But this is based on the assumption that EDFbrowser has correct latencies after conversion to EDF+C. 

Cedric

**Comment by Teuniz** [comment]
> I get those 5 files with exactly the same naming you have, but EDFBrowser cannot read them

I just wanted to inform you that some volunteer has released EDFbrowser 1.83 for the Mac.
(which solves the described problem)
You can find it here:
[https://gitlab.com/whitone/EDFbrowser/-/releases](url)
or here:
[https://formulae.brew.sh/cask/edfbrowser#default](url)   
   
Best,
Teunis

**Comment by faimai00** [comment]
Dear Cedric, 

Thank you so much for adjusting the sampling rate. You are right, the latencies obtained with your function are correct! I have also managed to compare them with the original files in Natus and they do correspond. I can read most of the files with the correct annotations! Thank you!

Just one thing - I am testing the function with different files I have (all edf+) and it seems like I cannot read the files containing one clip only (Error message appears as per screenshot below: "Unable to perform assignment with 0 elements on the right hand side"). These cannot be read by your function, but can be read by EDFbrowser. I have included an example file in the Drive (named **09RawData1clip**): https://drive.google.com/drive/folders/1SYpc6UMnbe-ip4lRB_cD_Eq1HCRP9e9I 
Is it because the function is tailored to read +D only? 

Also, it appears that it cannot read some of the files that contain more than one clip (+D). I haven't been able to pinpoint in what aspect these might differ from the rest of the multi-clip (EDF+D) files that are readable. I have included an example file in the Drive (named **17RawDataUnreadable**). This generates a different type of error (see screenshot: "Index exceeds the number of array elements (0)"). 

Thank you so much Cedric for your continuous help, I am very grateful.

Best wishes,
Irene

<img width="823" alt="Screenshot 2021-04-06 at 16 31 57" src="https://user-images.githubusercontent.com/63585229/114161975-8be55d80-9920-11eb-8ab4-4d23b5ce08b3.png">

<img width="780" alt="Screenshot 2021-04-06 at 16 32 42" src="https://user-images.githubusercontent.com/63585229/114161992-9273d500-9920-11eb-9b1b-238e01141718.png">

**Comment by amisepa** [comment]
Hi,

> Is it because the function is tailored to read +D only?

Yes I made the function based on your discontinuous EDF+D file.

> Also, it appears that it cannot read some of the files that contain more than one clip (+D). I haven't been able to pinpoint in what aspect these might differ from the rest of the multi-clip (EDF+D) files that are readable.

How is this file different than the other EDF+D file I worked on?

Thanks for sharing the files, I will see if I can adjust the function for these other files when I have some time (could be in a few weeks just so you know), and potentially make a new EEGLAB plugin from it if it works well. 

Thanks,
Cedric

**Comment by faimai00** [comment]
Dear Cedric,

I am not sure how these files differ from the other EDF+D file you worked on. I tried to find out but I cannot pinpoint any specific factors unfortunately. If you could have a look, that would be great thank you. 

Re: EDF+C files: would there be an easy way for your function to read these as well? With biosig mexSLOAD not working on mac, I am unable to read these unfortunately.

Thank you. 

Irene

**Comment by amisepa** [comment]
Ok. 

Yes, I will add the option in my function, it is much easier than EDF+D as it is continuous.

I'll let you know when it's done.

Cedric

**Comment by amisepa** [comment]
I've made it compatible for continuous data: [import_EDF.zip](https://github.com/sccn/eeglab/files/6330214/import_EDF.zip)

However, I realized that there may be DC offset differences between segments of the discontinuous data (EDF+D data) that needs to be corrected. I'll make a plugin soon with this problem fixed when I have some time. 
In the meantime, you may add boundaries manually with `pop_eegplot(EEG,1,0,1)` if you can reject sections of data where segments change. This will add boundaries at the right place in the data and then EEGLAB's filter functions will automatically correct DC offset changes if there are any. 

The problem with the other EDF+D file comes from the Matlab edfread function for some reason. Could you please submit that specific issue on MathWorks to see if they can fix it? 

Cedric

**Comment by faimai00** [comment]
Dear Cedric,

thank you so much for making the function compatible with EDF+C. Also, thank you in advance for working on the plugin that will correct the DC offset changes. If you could notify when this is done I would be grateful so I can switch from using the manual method you kindly suggested. 

All right - I will look into the problem with the other EDF+D files separately and log an issue. 

I am really grateful for all your help! It has been really invaluable, thank you!
Irene

**Comment by arnodelorme** [comment]
Cedric, any more feedback. Can we close this report?

**Comment by amisepa** [comment]
Yes we can close it, I just need to make a new plugin with this alternative method that uses Signal Processing Toolbox with Matlab > 2020a.

**Comment by faimai00** [comment]
Dear Cedric @amisepa , 
I am experiencing some problems with this import_EDF function as this seems to import only half of the recordings file in MatLab.
For example, the file named RKS05 (https://drive.google.com/drive/folders/1SYpc6UMnbe-ip4lRB_cD_Eq1HCRP9e9I?usp=sharing ) consists of 246 seconds of EEG recordings in EDF+, but once I import it using import_EDF, my xmax = 127.999. As you can see, the EEG.event latencies go up to 234 seconds. If you open the file in EDFbrowser, you can see all the 246 seconds of recording. This problem presents consistently across most of the EEG files I have. 

Please may I ask if you have any suggestions on how to solve this problem?

I am now working in Matlab2021_a (as MatLab2020b was giving some problems with the matlab edfread function, as described above - which get resolved by updating to 2021_a). 

Many thanks.
Irene

**Comment by amisepa** [comment]
Sorry to hear that, I'll take a look when I can

**Comment by amisepa** [comment]
I have an idea of what the problem could be. Does the sampling rate look correct?

**Comment by faimai00** [comment]
Dear Cedric,
thank you for your answer. 
The sampling rate is not correct - it displays as 1000 Hz for these data (RKS05), whilst the original sampling rate is 500 Hz. 
However, it does import a correct sampling rate for other data I have (e.g RKS07 which I have uploaded in the same folder). 
Many thanks for your advice.
Best wishes,
Irene

**Comment by amisepa** [comment]
Ok thank you. I have an idea of what might be going on. I'll take a look when possible.

**Comment by faimai00** [comment]
Hi Cedric, 
all right. I am looking forward to any suggestions you could give on this. Many thanks!
Irene

**Comment by faimai00** [comment]
Dear @amisepa 
I am sorry for the additional message, I was just wondering whether you would have any suggestions on this? I have looked into it but I was not able to find the cause of the problem. Any suggestions would be very welcome as I am very stuck with this problem. 
Many thanks again. 
Irene

**Comment by amisepa** [comment]
Sorry, extremely busy period...

When your RKS05 data are imported with my function line 64, cells contain 1000 data points and timepoints are every 2 s, and the matlab function reads 1000 hz sample rate as a consequence, but the sample rate should actually be 500 hz.
My code then takes each cell one by one and converts it to continuous data, and assumes the sample rate is 1000 hz. I believe the solution would be to divide each cell in half instead to get the correct 500 timepoints for each second, and correct the sample rate to 500. Might be tricky to get the correct event latencies though, can't remember how that would go. You can try and see if events adjust automatically. I'll try to take a look maybe next week if I can. Hope this helps and that you can find a solution in the mean time.

Cedric

**Comment by amisepa** [comment]
Hi Irene,

I think I fixed the issue. Please try this version attached:
[import_EDF.zip](https://github.com/sccn/eeglab/files/6809217/import_EDF.zip)

I compared the events of your file RKS05 with EDFBrowser (accounting for gaps between segments that were removed by my function), and it looks correct.
Please run some tests and let me know.

Cedric

**Comment by faimai00** [comment]
Dear Cedric, 

Thank you so much with that! I ran some tests also with some other files I have and it seems like it is working now! The sampling rates are correct and the whole EEG file is read and visualised correctly. 
I will let you know if I encounter any problems when I am going to work with it more in a few weeks, but it doesn't seem likely. 

I only get an error message regarding EEG.setname (line 239): 
<img width="434" alt="Screenshot 2021-07-14 at 10 23 29" src="https://user-images.githubusercontent.com/63585229/125589139-4867c040-bf48-4519-9941-eb30be0cf48a.png">

However if I comment out line 239 (which just regards the file name anyways) it runs smoothly! 
Many thanks again for your help, this is extremely useful!

Irene

**Comment by amisepa** [comment]
Glad it's working.

That setname issue should be fixed now, and I added some code to insert boundaries where DC offsets changes occur between discontinuous segments (e.g. file RKS05). EEGLAB default filters should automatically correct them now by detecting the boundaries.

Here is the new repo for this function: https://github.com/amisepa/import_EDF.git
This way you can just download or pull the latest version from there directly in the future.

Hope it works well with the rest of your data.

Cedric

**Comment by faimai00** [comment]
This is amazing, thank you so much Cedric for all your help!!
Irene

**Comment by arnodelorme** [comment]
Thanks Cedric,

**Comment by arnodelorme** [comment]
This one you can submit to the plugin manager.
Tx,

**Comment by amisepa** [comment]
Ok I'll do that when I have some time ;)

**Comment by faimai00** [comment]
Hi Cedric, just a note - line 99 should import data if they are continuous I believe, but it refers to discontinuous data instead:

    %CONTINUOUS DATA
    if ~discontinuous
        disp('Continuous data detected.');
        if (max(nSrate)-min(nSrate))/max(nSrate) > 0.01
            warning('Sampling rate unstable! This can be a serious problem!');
        end
        for iEv = 1:size(annot,1)
            EEG.event(iEv,:).type = char(table2array(annot(iEv,2)));
            latency = datenum(datetime(table2array(annot(iEv,1)), 'Format', 'HH:mm:ss:SSS'));
            latency = latency - datenum(datetime(edfTime(1), 'Format', 'HH:mm:ss:SSS'));
            EEG.event(iEv,:).latency = round(latency*24*60*60*sRate);   %correct latency in ms
            EEG.event(iEv,:).urevent = iEv;
        end
        EEG = eeg_checkset(EEG);

If you would have a chance to check that, it would be really useful. Many thanks! 
Irene

**Comment by amisepa** [comment]
Yes, discontinuous variable is 1 (true) for discontinuous data and 0 (false) for continuous data. the ~ symbol means the value is 0 so it's ok. However, I forgot to add a line to define it above when data is continuous... I added line 84. You should be good now after doing a pull (or re-download the code from the github page and replace the old one). 
Thanks!

**Comment by faimai00** [comment]
Many thanks for that Cedric!

Irene
________________________________

**Comment by faimai00** [comment]
Hi Cedric, 

I hope all is well with you. 
I just wanted to let you know that there are some errors with the part of the code that adds boundaries between segments so that EEG lab can automatically correct the discontinuity offsets. 

I have detected 2 types of errors: Error 1 (line 231) and Error 2 (line 236), see screenshots below:
<img width="665" alt="Error 2_RKS04" src="https://user-images.githubusercontent.com/63585229/130776710-015a3769-5c09-4d70-bc7e-a8914ada69b7.png">
r
-
<img width="670" alt="Error 1_RKS01" src="https://user-images.githubusercontent.com/63585229/130776705-9776e7f9-f50a-4d9d-b9ba-12471efdee2e.png">

These errors appear for some files but not others. 
For example error 1 (line 231) appears for the file named RKS01 which I added in the drive, and error 2 (line 236) appears for the file named RKS04 which I added in the drive: https://drive.google.com/drive/folders/1SYpc6UMnbe-ip4lRB_cD_Eq1HCRP9e9I 

However it does not appear for other files, e.g. RKS07 which was already in the drive.

Please would it be possible to look into this when you have a minute?
Many thanks!

Irene

**Comment by amisepa** [comment]
Hi, 
Sorry I'm not going to be able to look into it for the next 3 months probably.

**Comment by amisepa** [comment]
Ok I actually worked on it quickly because it was a simple issue due to empty events. It works now for both files if you do a pull of the repo.

**Comment by amisepa** [comment]
@faimai00 Is it working ok now?

**Comment by faimai00** [comment]
Yes I think it is working perfectly! Many thanks!
