### ISSUE TITLE
Preclutsering error 

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#443]
Hello, I tried to do pre-clustering by selecting these options

![image](https://user-images.githubusercontent.com/82998648/159667472-43e1f059-af2e-45d6-bb9e-17fe14f152fa.png)

and then I got the following error

![image](https://user-images.githubusercontent.com/82998648/159667184-579d4c9d-8e34-4643-86e7-6f3677a7d1e5.png)

Do you know what might be the reason? I have tried pre-clustering again on the same data but another study and it worked..

**Comment by evastone97** [comment]
I think that the main problem is the ERSPs and ITCs option, because I have tried to run it without those two options and it worked

**Comment by arnodelorme** [comment]
Would you mind sharing your data?

**Comment by evastone97** [comment]
Hello,

Yes it would be much easier to get help.

The only thing is that I cannot share them online can I send them private via email?

Kind Regards,
Evangelia

**Comment by arnodelorme** [comment]
We fixed an error 2 weeks ago. Do you have the latest changes? If you do, then I would like to help but without the data, there is nothing I can do.

**Comment by evastone97** [comment]
Unfortunately, I still have the error... But I cannot share the data because I don't have permission. Is there any other reason that you think might influence the error I am getting?
